import { test, expect } from '../fixtures/app-fixture'; import { createTicketData } from '../utils/data-factory';
test.describe('@regression Sorting and pagination',()=>{
  test.beforeEach(async({dashboard})=>dashboard.open());
  test('AT-022 Newest sorting places recently created ticket first',async({dashboard,createTicket})=>{const d=createTicketData();await createTicket.open();await createTicket.fill(d);await createTicket.submit();await dashboard.open();await dashboard.selectSorting('newest');await dashboard.applyFilters();expect((await dashboard.visibleRows())[0]?.title).toBe(d.title);});
  test('AT-023 Oldest sorting changes ticket order',async({dashboard})=>{await dashboard.selectSorting('newest');await dashboard.applyFilters();const newest=(await dashboard.visibleRows()).map(r=>r.title);test.skip(newest.length<2,'Requires two tickets');await dashboard.selectSorting('oldest');await dashboard.applyFilters();expect((await dashboard.visibleRows()).map(r=>r.title)).not.toEqual(newest);});
  test('AT-024 Priority sorting follows business severity order',async({dashboard})=>{await dashboard.selectSorting('priority');await dashboard.applyFilters();const rank=['CRITICAL','HIGH','MEDIUM','LOW'];const values=(await dashboard.visibleRows()).map(r=>rank.indexOf(r.priority));expect(values).toEqual([...values].sort((a,b)=>a-b));});
  test('AT-025 Status sorting follows workflow order',async({dashboard})=>{await dashboard.selectSorting('status');await dashboard.applyFilters();const rank=['OPEN','IN_PROGRESS','RESOLVED','CLOSED'];const values=(await dashboard.visibleRows()).map(r=>rank.indexOf(r.status));expect(values).toEqual([...values].sort((a,b)=>a-b));});
  test('AT-026 Pagination controls appear when more than 10 records exist',async({dashboard})=>{const count=Number((await dashboard.queue.locator('..').innerText()).match(/(\d+) matching/)?.[1]??0);test.skip(count<=10,'Current shared dataset has 10 or fewer records');await expect(dashboard['page'].getByRole('link',{name:/Next/i})).toBeVisible();});
  test('AT-027 Next-page navigation works',async({dashboard})=>{const next=dashboard['page'].getByRole('link',{name:/Next/i});test.skip(!(await next.count()),'Pagination is absent until the shared dataset exceeds one page');await next.click();expect(new URL(dashboard['page'].url()).searchParams.get('page')).not.toBeNull();});
  test('AT-028 Previous-page navigation works',async({dashboard})=>{const next=dashboard['page'].getByRole('link',{name:/Next/i});test.skip(!(await next.count()),'Pagination is absent until the shared dataset exceeds one page');await next.click();await dashboard.navigatePagination('Previous');await expect(dashboard.queue).toBeVisible();});
  test('AT-029 Negative page input is handled safely, if applicable',()=>test.skip(true,'The UI has no page-number input; synthetic query manipulation is outside this UI suite.'));
});
